"""m2.3 relation verdicts

Revision ID: 2b19e8eb334b
Revises: d9ae7288290b
Create Date: 2026-08-02 15:23:05.494591
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2b19e8eb334b'
down_revision: str | None = 'd9ae7288290b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_verdicts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('left_atomic_id', sa.BigInteger(), nullable=False),
    sa.Column('right_atomic_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('shared_entity', sa.String(length=64), nullable=True),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['left_atomic_id'], ['atomic_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_atomic_id'], ['atomic_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_atomic_id', 'right_atomic_id', name='uq_relation_pair')
    )
    op.create_index(op.f('ix_relation_verdicts_decision'), 'relation_verdicts', ['decision'], unique=False)
    op.create_index(op.f('ix_relation_verdicts_left_atomic_id'), 'relation_verdicts', ['left_atomic_id'], unique=False)
    op.create_index(op.f('ix_relation_verdicts_right_atomic_id'), 'relation_verdicts', ['right_atomic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_verdicts_right_atomic_id'), table_name='relation_verdicts')
    op.drop_index(op.f('ix_relation_verdicts_left_atomic_id'), table_name='relation_verdicts')
    op.drop_index(op.f('ix_relation_verdicts_decision'), table_name='relation_verdicts')
    op.drop_table('relation_verdicts')
    # ### end Alembic commands ###
