"""harden semantic lifecycle and daily snapshots

Revision ID: 33e4be894d94
Revises: 2b19e8eb334b
Create Date: 2026-08-03 11:27:42.096799
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "33e4be894d94"
down_revision: str | None = "2b19e8eb334b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_hotspot_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("natural_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "natural_date", "timezone", "category", "revision", name="uq_daily_snapshot_revision"
        ),
    )
    op.create_index(
        op.f("ix_daily_hotspot_snapshots_generated_at"),
        "daily_hotspot_snapshots",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_hotspot_snapshots_natural_date"),
        "daily_hotspot_snapshots",
        ["natural_date"],
        unique=False,
    )
    op.create_table(
        "relation_scan_states",
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("last_atomic_id", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("algorithm_version"),
    )
    op.create_table(
        "daily_hotspot_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["daily_hotspot_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "rank", name="uq_daily_snapshot_rank"),
    )
    op.create_index(
        op.f("ix_daily_hotspot_items_event_id"), "daily_hotspot_items", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_hotspot_items_snapshot_id"),
        "daily_hotspot_items",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "semantic_promotions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("component_key", sa.String(length=64), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("draft_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=True),
        sa.Column("event_version", sa.Integer(), nullable=True),
        sa.Column(
            "atomic_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "document_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("draft", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "claims", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "component_key", "algorithm_version", name="uq_semantic_promotion_component"
        ),
    )
    op.create_index(
        op.f("ix_semantic_promotions_event_id"), "semantic_promotions", ["event_id"], unique=False
    )
    op.create_table(
        "semantic_model_attempts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("work_item_id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("work_attempt", sa.Integer(), nullable=False),
        sa.Column("call_ordinal", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column(
            "usage", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("finish_reason", sa.String(length=64), nullable=True),
        sa.Column("validation_error", sa.Text(), nullable=True),
        sa.Column("provider_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_item_id"], ["semantic_work_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "work_item_id", "work_attempt", "call_ordinal", name="uq_semantic_model_attempt"
        ),
    )
    op.create_index(
        op.f("ix_semantic_model_attempts_document_id"),
        "semantic_model_attempts",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_model_attempts_work_item_id"),
        "semantic_model_attempts",
        ["work_item_id"],
        unique=False,
    )
    op.create_table(
        "relation_candidates",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("left_atomic_id", sa.BigInteger(), nullable=False),
        sa.Column("right_atomic_id", sa.BigInteger(), nullable=False),
        sa.Column("shared_entity", sa.String(length=64), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("left_atomic_id < right_atomic_id", name="ck_relation_candidate_order"),
        sa.ForeignKeyConstraint(["left_atomic_id"], ["atomic_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["right_atomic_id"], ["atomic_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "left_atomic_id",
            "right_atomic_id",
            "algorithm_version",
            name="uq_relation_candidate_version",
        ),
    )
    op.create_index(
        "ix_relation_candidate_claim",
        "relation_candidates",
        ["status", "next_retry_at", "lease_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relation_candidates_left_atomic_id"),
        "relation_candidates",
        ["left_atomic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relation_candidates_right_atomic_id"),
        "relation_candidates",
        ["right_atomic_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relation_candidates_right_atomic_id"), table_name="relation_candidates")
    op.drop_index(op.f("ix_relation_candidates_left_atomic_id"), table_name="relation_candidates")
    op.drop_index("ix_relation_candidate_claim", table_name="relation_candidates")
    op.drop_table("relation_candidates")
    op.drop_index(
        op.f("ix_semantic_model_attempts_work_item_id"), table_name="semantic_model_attempts"
    )
    op.drop_index(
        op.f("ix_semantic_model_attempts_document_id"), table_name="semantic_model_attempts"
    )
    op.drop_table("semantic_model_attempts")
    op.drop_index(op.f("ix_semantic_promotions_event_id"), table_name="semantic_promotions")
    op.drop_table("semantic_promotions")
    op.drop_index(op.f("ix_daily_hotspot_items_snapshot_id"), table_name="daily_hotspot_items")
    op.drop_index(op.f("ix_daily_hotspot_items_event_id"), table_name="daily_hotspot_items")
    op.drop_table("daily_hotspot_items")
    op.drop_table("relation_scan_states")
    op.drop_index(
        op.f("ix_daily_hotspot_snapshots_natural_date"), table_name="daily_hotspot_snapshots"
    )
    op.drop_index(
        op.f("ix_daily_hotspot_snapshots_generated_at"), table_name="daily_hotspot_snapshots"
    )
    op.drop_table("daily_hotspot_snapshots")
    # ### end Alembic commands ###
