"""m1.1 document classification columns

Revision ID: a9baeb84971f
Revises: bd8cbfdfedd6
Create Date: 2026-07-29 15:02:33.870914
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a9baeb84971f'
down_revision: str | None = 'bd8cbfdfedd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tech_directions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('documents', sa.Column('company_models', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('documents', sa.Column('classified_event_type', sa.String(length=32), nullable=True))
    op.add_column('documents', sa.Column('classify_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('classify_method', sa.String(length=16), nullable=True))
    op.add_column('documents', sa.Column('classify_model_version', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('classify_prompt_version', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('classify_rule_version', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('classify_input_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('near_dup_of', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'near_dup_of')
    op.drop_column('documents', 'classified_at')
    op.drop_column('documents', 'classify_input_hash')
    op.drop_column('documents', 'classify_rule_version')
    op.drop_column('documents', 'classify_prompt_version')
    op.drop_column('documents', 'classify_model_version')
    op.drop_column('documents', 'classify_method')
    op.drop_column('documents', 'classify_confidence')
    op.drop_column('documents', 'classified_event_type')
    op.drop_column('documents', 'company_models')
    op.drop_column('documents', 'tech_directions')
    # ### end Alembic commands ###
