"""initial schema

Revision ID: bd8cbfdfedd6
Revises: 
Create Date: 2026-07-28 16:27:54.126822
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bd8cbfdfedd6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'target', 'payload_hash', name='uq_delivery_idempotency')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('topic', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('trust_tier', sa.String(length=1), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('org', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_endpoints',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('parser', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('trust_tier', sa.String(length=1), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('egress_route', sa.String(length=32), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fetch_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['source_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('native_id', sa.String(length=512), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('blob_ref', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('connector_version', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('stage_lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['source_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'canonical_url', 'published_at', name='uq_raw_endpoint_url_pub'),
    sa.UniqueConstraint('endpoint_id', 'native_id', name='uq_raw_endpoint_native')
    )
    op.create_index(op.f('ix_raw_items_stage'), 'raw_items', ['stage'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_item_id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint_id', sa.String(length=128), nullable=False),
    sa.Column('title_original', sa.Text(), nullable=False),
    sa.Column('title_zh', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('org', sa.String(length=256), nullable=True),
    sa.Column('published_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_quality', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_item_id')
    )
    op.create_table('event_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('evidence_level', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'document_id', name='uq_event_document')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_raw_items_stage'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_table('fetch_runs')
    op.drop_table('source_endpoints')
    op.drop_table('sources')
    op.drop_table('events')
    op.drop_table('delivery_runs')
    # ### end Alembic commands ###
