"""align m2 metadata

Revision ID: d2c5d53a7a76
Revises: 2b6d8f4a1c90
Create Date: 2026-07-31 17:11:15.154369
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "d2c5d53a7a76"
down_revision: str | None = "2b6d8f4a1c90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Earlier M2.1 migrations left these audit timestamps nullable. Backfill
    # defensively before enforcing the ORM invariant on existing installations.
    op.execute(
        sa.text(
            """
            UPDATE candidate_reviews SET created_at = now() WHERE created_at IS NULL;
            UPDATE claim_evidence SET created_at = now() WHERE created_at IS NULL;
            UPDATE claims SET created_at = now() WHERE created_at IS NULL;
            UPDATE claims SET updated_at = now() WHERE updated_at IS NULL;
            UPDATE document_block_token_stats SET updated_at = now() WHERE updated_at IS NULL;
            UPDATE document_identities SET created_at = now() WHERE created_at IS NULL;
            UPDATE document_signatures SET indexed_at = now() WHERE indexed_at IS NULL;
            UPDATE duplicate_components SET created_at = now() WHERE created_at IS NULL;
            UPDATE duplicate_components SET updated_at = now() WHERE updated_at IS NULL;
            UPDATE event_versions SET created_at = now() WHERE created_at IS NULL;
            UPDATE m2_runs SET started_at = now() WHERE started_at IS NULL;
            UPDATE m2_work_items SET created_at = now() WHERE created_at IS NULL;
            """
        )
    )
    op.alter_column(
        "candidate_reviews",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_candidate_reviews_left_document_id"),
        "candidate_reviews",
        ["left_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_reviews_right_document_id"),
        "candidate_reviews",
        ["right_document_id"],
        unique=False,
    )
    op.alter_column(
        "claim_evidence",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "claims",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "claims",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_block_token_stats",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_identities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_signatures",
        "indexed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "duplicate_components",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "duplicate_components",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "event_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "m2_runs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "m2_work_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "m2_work_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "m2_runs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "event_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "duplicate_components",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "duplicate_components",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_signatures",
        "indexed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_identities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_block_token_stats",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "claims",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "claims",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "claim_evidence",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_candidate_reviews_right_document_id"), table_name="candidate_reviews")
    op.drop_index(op.f("ix_candidate_reviews_left_document_id"), table_name="candidate_reviews")
    op.alter_column(
        "candidate_reviews",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
