"""m2.2.1 semantic audit + batch columns

Revision ID: d62bdcaecebf
Revises: d2c5d53a7a76
Create Date: 2026-08-01 22:47:46.351266
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd62bdcaecebf'
down_revision: str | None = 'd2c5d53a7a76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cr_left_doc'), table_name='candidate_reviews')
    op.drop_index(op.f('idx_cr_right_doc'), table_name='candidate_reviews')
    op.add_column('document_enrichments', sa.Column('raw_response', sa.Text(), nullable=True))
    op.add_column('document_enrichments', sa.Column('finish_reason', sa.String(length=32), nullable=True))
    op.add_column('document_enrichments', sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('document_enrichments', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('document_enrichments', sa.Column('batch_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_document_enrichments_batch_id'), 'document_enrichments', ['batch_id'], unique=False)
    op.drop_index(op.f('idx_ed_doc'), table_name='event_documents')
    op.drop_index(op.f('idx_ev_pk'), table_name='events')
    op.drop_index(op.f('idx_mr_doc'), table_name='model_runs')
    op.add_column('semantic_work_items', sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False))
    op.add_column('semantic_work_items', sa.Column('last_finish_reason', sa.String(length=32), nullable=True))
    op.add_column('semantic_work_items', sa.Column('last_usage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('semantic_work_items', sa.Column('batch_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_semantic_work_items_batch_id'), 'semantic_work_items', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_work_items_batch_id'), table_name='semantic_work_items')
    op.drop_column('semantic_work_items', 'batch_id')
    op.drop_column('semantic_work_items', 'last_usage')
    op.drop_column('semantic_work_items', 'last_finish_reason')
    op.drop_column('semantic_work_items', 'max_attempts')
    op.create_index(op.f('idx_mr_doc'), 'model_runs', ['document_id'], unique=False)
    op.create_index(op.f('idx_ev_pk'), 'events', ['id'], unique=False)
    op.create_index(op.f('idx_ed_doc'), 'event_documents', ['document_id'], unique=False)
    op.drop_index(op.f('ix_document_enrichments_batch_id'), table_name='document_enrichments')
    op.drop_column('document_enrichments', 'batch_id')
    op.drop_column('document_enrichments', 'error')
    op.drop_column('document_enrichments', 'usage')
    op.drop_column('document_enrichments', 'finish_reason')
    op.drop_column('document_enrichments', 'raw_response')
    op.create_index(op.f('idx_cr_right_doc'), 'candidate_reviews', ['right_document_id'], unique=False)
    op.create_index(op.f('idx_cr_left_doc'), 'candidate_reviews', ['left_document_id'], unique=False)
    # ### end Alembic commands ###
