"""m2.2.1 nvd isolation event category

Revision ID: d9ae7288290b
Revises: d62bdcaecebf
Create Date: 2026-08-01 23:35:25.984098
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd9ae7288290b'
down_revision: str | None = 'd62bdcaecebf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
